---
title: "Resume"
---

# Education

-   McGill University - Bachelor of Science in Environmental and Agricultural Science
    -   September 2021 - April 2024
    -   Major: Environmental Biology
        -   Specialization: Applied Ecology

        -   Minor: Environment
    -   GPA: 3.59
-   University of Toronto - Visiting Student Program
    -   January 2024 - April 2024
    -   Geomorphology, Writing about Environment and Ecology
-   University of British Columbia - Master of Geomatics for Environmental Management
    -   September 2024 - April 2025

# Publications

*Reports:*

-   Long Duration Energy Storage
-   Management of the Columbia River
-   Wetland Restoration Project Report: Lake Winnipeg Basin and Taihu Lake Basin

# Institutional Service

-   Removal of Invasive Plant Species Volunteer Project: Garlic Mustard
    -   April 2023 to May 2023
    -   Organization: Department of Natural Resource Sciences at McGill University
    -   Contributed to the removal of the invasive species garlic mustard around the campus, promoting the restoration of local ecosystems
